// <auto-generated />
using System;
using DistributedMazeGame.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DistributedMazeGame.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219172745_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DistributedMazeGame.Server.Data.Entities.GameSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("SessionId");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("DistributedMazeGame.Server.Data.Entities.Move", b =>
                {
                    b.Property<long>("MoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("MoveId"));

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MoveId");

                    b.HasIndex("PlayerId", "SessionId");

                    b.HasIndex("SessionId", "Timestamp");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("DistributedMazeGame.Server.Data.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PlayerId");

                    b.HasIndex("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DistributedMazeGame.Server.Data.Entities.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("WinnerPlayerId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("WinnerPlayerId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("DistributedMazeGame.Server.Data.Entities.Move", b =>
                {
                    b.HasOne("DistributedMazeGame.Server.Data.Entities.Player", "Player")
                        .WithMany("Moves")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DistributedMazeGame.Server.Data.Entities.GameSession", "Session")
                        .WithMany("Moves")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DistributedMazeGame.Server.Data.Entities.Result", b =>
                {
                    b.HasOne("DistributedMazeGame.Server.Data.Entities.GameSession", "Session")
                        .WithOne("Result")
                        .HasForeignKey("DistributedMazeGame.Server.Data.Entities.Result", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DistributedMazeGame.Server.Data.Entities.Player", "Winner")
                        .WithMany("Results")
                        .HasForeignKey("WinnerPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("DistributedMazeGame.Server.Data.Entities.GameSession", b =>
                {
                    b.Navigation("Moves");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("DistributedMazeGame.Server.Data.Entities.Player", b =>
                {
                    b.Navigation("Moves");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
